# Generated by Django 4.2.4 on 2023-08-05 18:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('role', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Trainee', 'Trainee'), ('Guest', 'Guest'), ('User', 'User'), ('Client', 'Client')], default='User', max_length=50, verbose_name='Role')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Profile Picture')),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referral Code')),
                ('referral_share', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Refferal Sharing Code')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-is_active'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
